baseURL = 'https://seescene.cc/'
languageCode = 'en-us'
title = 'See Scene'
theme = 'archie'

[params.meta]
favicon = true
faviconVersion = "1"

[params]
mode="light" # color-mode → light,dark,toggle or auto

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/FutureSharks/seescene"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "About"
url = "/about/"
weight = 3

[[menu.main]]
name = "Contribute"
url = "/contribute/"
weight = 3
